### ISSUE TITLE
Feedback and minor improvement ideas

### ISSUE THREAD

**Issue by nestaval** [Crynners/AccBot#4]
Hi,

thanks a lot for sharing the AccBot.

The setup was quite straightforward and the bot started accumulating on my behalf.

I just found one particular configuration value misleading:

```
# Once every how many hours you want to buy BTC regularly
$HourDivider='1'
```

I was like "let's set it to something like 29 so that the trade won't be done every day at the same time".
After two trades I noticed that they are done at the same time "daily".
So I started investigating the code and found out this "fancy code" that prepares [NCRONTAB expression](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=csharp#ncrontab-expressions):

```
if ( 1 -eq $HourDivider )
{
    $HourDivider = '*'
    $NextHour = ""
}else{
    $NextHour = $HourDivider + ". "
    $HourDivider = '*/' + $HourDivider
}

$DayDividerSchedule = '0 ' + $randomMinutes + ' ' + $HourDivider + ' * * *'
```

I might be stupid, but I think that by the design (that the AccBot uses [timer trigger function](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer)) there is no simple way of defining the trading interval so it will extend 24 hours or 60 minutes. And when I say "simple" I mean "out of the box" and without implementing any logic for that. 
*Or is there?*

Anyway, I started [playing around with the NCRONTAB expression](https://ncrontab.swimburger.net/) and realized that it might be beneficial to allow people to set the scheduling on their own like:

```
if ( ($NCronTabExpression -eq $null) -or ($NCronTabExpression -eq '')) {

	Write-Verbose "`$NCronTabExpression not set => use random minutes & `$HourDivider instead to set `$DayDividerSchedule"

	$randomMinutes = Get-Random -Maximum 60

	if ( 1 -eq $HourDivider )
	{
		$HourDivider = '*'
		$NextHour = ""
	}else{
		$NextHour = $HourDivider + ". "
		$HourDivider = '*/' + $HourDivider
	}

	$DayDividerSchedule = '0 ' + $randomMinutes + ' ' + $HourDivider + ' * * *'

} else {
		
	Write-Verbose "So you think you are PRO right? OK then, using your `$NCronTabExpression to set `$DayDividerSchedule"

	$DayDividerSchedule = $NCronTabExpression
}
```

Further, I would recommend separating the "USER-DEFINED VARIABLES" from the installation script.
I am not an expert on PowerShell, but I would appreciate getting it loaded from something like a property file in which no harm could be made to the actual execution code.

Last but not least I would recommend commenting on the source code in English only.

Thumbs up and looking forward to your next release/improvements.

Thanks!

P.S.: Is there a way to set up the AccBot to trade more currency pairs (e.g. EUR -> BTC & EUR -> LTC) at the same time?

**Comment by jaracimrman** [comment]
Hi, just want to chime in regarding this "issue".

I set up the bot to buy every 168 hours, meaning once a week. 
Turns out it buys every day, which i guess is closely related to above.

Would be more than happy if i could adjust the buy interval to my prefference, even like once a month buy or something :)

Thank you!

**Comment by Crynners** [comment]
Hey, nestaval,
thanks so much for the comment and feedback on Accbot, we really appreciate it!

You're right that **HourDivider** is slightly confusing, and that's because we tried to simplify the usage so that the user doesn't have to learn the mentioned CRONTAB structure. But we agree that it's a good idea to allow users to do this and directly have the influence to set their CRONTAB via a variable themselves. **It will be implemented soon.**

Separating user-defined variables was a good idea and **it is even already implemented.** :)

Setting multiple pairs is currently possible, however you need to go into the non-user-defined variables section. In the system variables, it's hardcoded: "$resourceGroupName='AccBot'", which makes up the ResourceGroup on Azure. If you override this to, for example, $resourceGroupName='AccBot_LTCCZK', it will create a new resource group with new resources in parallel. So there will be two bots in parallel. But then you always need to be careful when updating the bot that you have the $resourceGroupName variable set correctly.

P.S. We are gradually transcribing the source code comments into English :)

Regards,
Crynners

**Comment by Crynners** [comment]
Hi jaracimrman,
Sorry for the confusion with "HourDivider", as mentioned in the comment above, soon it will be implenented the possibility to directly set the CRONTAB in the installation configuration file, so it will be possible to set the scheduler at will.

Regards,
Crynners

**Comment by Crynners** [comment]
Hello,
We have added a $NCronTabExpression variable to the configuration file, through which it is possible to set a customizable scheduler. At the same time, we have also extended the comment a bit.

Thank you very much for your feedback and if there is anything, please get back to us.

Regards,
Crynners
